package agentica.session

import upickle.default.*

// ─── Opaque types ─────────────────────────────────────────────────────────────

/**
 *  Type-safe wrapper for a message role.
 *  Prevents mixing up role strings with other [[String]] parameters at compile time.
 *  Runtime representation is a plain [[String]] with zero overhead.
 */
opaque type MessageRole = String

/**
 *  Companion providing constants, safe/unsafe constructors, and a [[ReadWriter]].
 */
object MessageRole
{
    /** Role for messages sent by the human user. */
    val User: MessageRole = "user"

    /** Role for messages generated by the AI assistant. */
    val Assistant: MessageRole = "assistant"

    /** Role for the system prompt injected at context assembly. */
    val System: MessageRole = "system"

    /**
     *  Parses a role string from an external source (HTTP parameter, SQLite row).
     *  @param s  Raw string value.
     *  @return   `Some(role)` for recognised values; `None` for unknown strings.
     */
    def fromString(s: String): Option[MessageRole] = s match
    {
        case "user" | "assistant" | "system" => Some(s)
        case _                               => None
    }

    /**
     *  Wraps a string without validation.
     *  Use only for data from trusted sources (e.g. rows already validated on write).
     *  @param s  Raw string value to wrap.
     *  @return   The wrapped [[MessageRole]].
     */
    def unsafe(s: String): MessageRole = s

    extension (r: MessageRole)
    {
        /** Returns the underlying string value for JDBC writes and JSON serialisation. */
        def value: String = r
    }

    /** upickle [[ReadWriter]] — delegates to the underlying [[String]] serialiser. */
    given ReadWriter[MessageRole] = summon[ReadWriter[String]].asInstanceOf[ReadWriter[MessageRole]]
}

/**
 *  Type-safe wrapper for a tool run status.
 *  Prevents mixing up status strings with other [[String]] parameters at compile time.
 *  Runtime representation is a plain [[String]] with zero overhead.
 */
opaque type RunStatus = String

/**
 *  Companion providing constants, safe/unsafe constructors, and a [[ReadWriter]].
 */
object RunStatus
{
    /** The tool executed successfully. */
    val Success: RunStatus = "success"

    /** The tool returned an error result. */
    val Error: RunStatus = "error"

    /** The run was cancelled before completion. */
    val Cancelled: RunStatus = "cancelled"

    /**
     *  Parses a status string from an external source.
     *  @param s  Raw string value.
     *  @return   `Some(status)` for recognised values; `None` otherwise.
     */
    def fromString(s: String): Option[RunStatus] = s match
    {
        case "success" | "error" | "cancelled" => Some(s)
        case _                                 => None
    }

    /**
     *  Wraps a string without validation.
     *  Use only for data from trusted sources (e.g. rows already validated on write).
     *  @param s  Raw string value to wrap.
     *  @return   The wrapped [[RunStatus]].
     */
    def unsafe(s: String): RunStatus = s

    extension (r: RunStatus)
    {
        /** Returns the underlying string value for JDBC writes and JSON serialisation. */
        def value: String = r
    }

    /** upickle [[ReadWriter]] — delegates to the underlying [[String]] serialiser. */
    given ReadWriter[RunStatus] = summon[ReadWriter[String]].asInstanceOf[ReadWriter[RunStatus]]
}

/**
 *  Type-safe wrapper for an agent turn step type.
 *  Prevents mixing up step type strings with other [[String]] parameters at compile time.
 *  Runtime representation is a plain [[String]] with zero overhead.
 */
opaque type StepType = String

/**
 *  Companion providing constants, safe/unsafe constructors, and a [[ReadWriter]].
 */
object StepType
{
    /** Intermediate LLM response before tool calls. */
    val Thinking: StepType = "thinking"

    /** A dispatched tool invocation. */
    val ToolCall: StepType = "tool_call"

    /**
     *  Parses a step type string from an external source.
     *  @param s  Raw string value.
     *  @return   `Some(stepType)` for recognised values; `None` otherwise.
     */
    def fromString(s: String): Option[StepType] = s match
    {
        case "thinking" | "tool_call" => Some(s)
        case _                         => None
    }

    /**
     *  Wraps a string without validation.
     *  Use only for data from trusted sources (e.g. rows already validated on write).
     *  @param s  Raw string value to wrap.
     *  @return   The wrapped [[StepType]].
     */
    def unsafe(s: String): StepType = s

    extension (r: StepType)
    {
        /** Returns the underlying string value for JDBC writes and JSON serialisation. */
        def value: String = r
    }

    /** upickle [[ReadWriter]] — delegates to the underlying [[String]] serialiser. */
    given ReadWriter[StepType] = summon[ReadWriter[String]].asInstanceOf[ReadWriter[StepType]]
}

// ─── Domain models ────────────────────────────────────────────────────────────

/** A chat session grouping all messages under a single conversation context.
 *  @param id               Unique session identifier (UUID).
 *  @param title            Human-readable session title.
 *  @param createdAt        ISO-8601 creation timestamp.
 *  @param updatedAt        ISO-8601 last-updated timestamp.
 *  @param model            LLM model name used for this session (e.g. "llama3.2").
 *  @param rootPath         Optional filesystem path set as the session working directory.
 *  @param lastResponseId   ID of the last Responses API response; used to thread stateful
 *                          multi-turn conversations across agent runs within the same session.
 */
case class Session(
    id:             String,
    title:          String,
    createdAt:      String,
    updatedAt:      String,
    model:          String,
    rootPath:       Option[String],
    lastResponseId: Option[String] = None
) derives ReadWriter

/** A single message in a session's conversation history.
 *  @param id          Unique message identifier (UUID).
 *  @param sessionId   Parent session identifier.
 *  @param role        Speaker role: [[MessageRole.User]], [[MessageRole.Assistant]], or [[MessageRole.System]].
 *  @param content     Text content of the message.
 *  @param timestamp   ISO-8601 timestamp of when the message was recorded.
 *  @param attachments List of attachment references (file paths or URIs); empty by default.
 */
case class Message(
    id: String,
    sessionId: String,
    role: MessageRole,
    content: String,
    timestamp: String,
    attachments: List[String] = Nil
) derives ReadWriter

/** A record of a single tool invocation within an agent turn.
 *  @param id         Unique run identifier (UUID).
 *  @param sessionId  Parent session identifier.
 *  @param tool       Name of the tool that was invoked.
 *  @param input      JSON-serialised input payload passed to the tool.
 *  @param output     JSON-serialised output returned by the tool.
 *  @param status     Outcome: [[RunStatus.Success]], [[RunStatus.Error]], or [[RunStatus.Cancelled]].
 *  @param traceId    Trace identifier linking the run to its agent turn.
 *  @param durationMs Wall-clock duration of the tool invocation in milliseconds.
 */
case class ToolRun(
    id: String,
    sessionId: String,
    tool: String,
    input: String,
    output: String,
    status: RunStatus,
    traceId: String,
    durationMs: Long
) derives ReadWriter

/** A session-scoped key-value memory entry persisted in SQLite.
 *  @param sessionId  Owning session identifier.
 *  @param key        Unique key within the session.
 *  @param value      Stored string value.
 *  @param updatedAt  ISO-8601 timestamp of the last write.
 */
case class MemoryEntry(
    sessionId: String,
    key:       String,
    value:     String,
    updatedAt: String
) derives ReadWriter

/**
 *  A single step within an agent turn's trajectory.
 *  @param stepType    [[StepType.Thinking]] — intermediate LLM response before tool calls;
 *                     [[StepType.ToolCall]] — a dispatched tool invocation.
 *  @param iteration   1-based iteration number this step belongs to.
 *  @param content     Intermediate LLM response text (thinking steps only; empty for tool_call).
 *  @param command     Raw command string (tool_call steps only; empty for thinking).
 *  @param result      Tool output text (tool_call steps only; empty for thinking).
 *  @param durationMs  Wall-clock duration in ms (tool_call only; 0 for thinking).
 */
case class AgentTurnStep(
    stepType:   StepType,
    iteration:  Int,
    content:    String,
    command:    String,
    result:     String,
    durationMs: Long
) derives ReadWriter

/**
 *  Complete trajectory record for one agent turn (user prompt → final answer).
 *  Stores all intermediate reasoning steps and tool calls so the UI can replay
 *  the full trajectory on history reload.
 *  @param id             Unique identifier (UUID).
 *  @param sessionId      Parent session identifier.
 *  @param userMsgId      [[Message]] id of the triggering user message.
 *  @param assistantMsgId [[Message]] id of the final assistant answer (empty if cancelled).
 *  @param steps          Ordered list of intermediate steps (thinking + tool_call).
 *  @param traceId        Trace identifier linking this turn to its log entries.
 *  @param timestamp      ISO-8601 timestamp of when the turn completed.
 */
case class AgentTurn(
    id:             String,
    sessionId:      String,
    userMsgId:      String,
    assistantMsgId: String,
    steps:          List[AgentTurnStep],
    traceId:        String,
    timestamp:      String
) derives ReadWriter

/** Token and latency accounting for a single LLM call.
 *  @param id                Unique record identifier (UUID).
 *  @param traceId           Trace identifier of the agent turn that triggered the call.
 *  @param sessionId         Parent session identifier.
 *  @param model             LLM model name used for the call.
 *  @param promptTokens      Number of tokens in the prompt sent to the model.
 *  @param completionTokens  Number of tokens in the model's response.
 *  @param latencyMs         End-to-end latency of the LLM call in milliseconds.
 *  @param createdAt         ISO-8601 timestamp of when the record was created.
 */
case class TokenUsage(
    id: String,
    traceId: String,
    sessionId: String,
    model: String,
    promptTokens: Int,
    completionTokens: Int,
    latencyMs: Long,
    createdAt: String
) derives ReadWriter
